version: '3'

services:

  app:
    build: .
    #container_name: api_external
    volumes:
      - /home/juliano/AVEC-PROJECTS/core/api_sistema/www:/var/www
    expose:
      - 9000
    # networks:
    #   - api_external
    #   - default
    restart: always

  nginx:
    build: nginx
    #container_name: nginx_api_external
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - /home/juliano/AVEC-PROJECTS/core/api_sistema/www:/var/www
    #networks:
      # - api_external
      # - default
    depends_on:
      - app

networks:
  api_external:
    driver: bridge 